### ISSUE TITLE
negative percentage

### ISSUE THREAD

**Issue by ortchi42** [gabriel-milan/btrader#1]
Is the negative percentage normal, or is it an error?
I'm confused by what your config says:                    "PROFIT_THRESHOLD": -10.0, 
Would the bot just lose money?
https://de.share-your-photo.com/img/24251c0003.png

**Comment by gabriel-milan** [comment]
Hi @ortchi42.

The configuration file I provide is just an example, you should fit your needs. But answering your question, if you set the profit threshold to -10%, you'll lose money, yes.

Anyway, I'll change these values. I was using those for debugging purposes only.

**Comment by ortchi42** [comment]
Thanks for the quick answer :)
Do you also have positive hits?

**Comment by gabriel-milan** [comment]
Yes, I've had a few positive hits. But please, before testing with trading enabled, be aware of the following:

* The age of the data refers to computational resources only, i.e, network delays are not accounted. For best results, you have got to be closer to the Binance server in Tokyo. In my case, I'm using an Azure VM in Tokyo and getting ~10ms network delay.
* bTrader is early and still a work in progress. For that reason, it may not be as stable as you'd want and I can't take responsibility for any losses you may have. I'm taking my risks whilst developing this, but I'm not trading lots of money.

Any help on developing is welcome too! :)

**Comment by ortchi42** [comment]
Thanks for the tips.
I'm testing this in a VM at home right now and Tokyo is far away ;) I'll find another server.
I'm a network administrator and have been working with BTC and Co. for 8 years, from mining pool, to my own currencies.
I can't help you much with programming, but I'm always there for testing :)

**Comment by gabriel-milan** [comment]
Awesome! Testing is as important as developing. You can test the new features I've added today (mostly Telegram bot), I've released an updated tag on DockerHub just now.

I'm pretty newbie to all of this, though, hope I'm getting it right :)

**Comment by ortchi42** [comment]
After I have updated Docker the following error occurs:
`Traceback (most recent call last):
  File "/btrader/scripts/entrypoint.py", line 3, in <module>
    from btrader import bTrader
  File "btrader/__init__.py", line 5, in init btrader.__init__
  File "btrader/core/__init__.py", line 23, in init btrader.core.__init__
  File "btrader/core/bTrader.py", line 20, in init btrader.core.bTrader
  File "/usr/local/lib/python3.7/dist-packages/btrader/bot/__init__.py", line 3, in <module>
    from . import TelegramBot
  File "/usr/local/lib/python3.7/dist-packages/btrader/bot/TelegramBot.py", line 6, in <module>
    import telegram
ModuleNotFoundError: No module named 'telegram'`

**Comment by gabriel-milan** [comment]
Yeah, I've noticed a missing dependency yesterday but forgot to fix it. I'm uploading a newer version right now, it should be available in a few minutes. Thank you.
