### ISSUE TITLE
[Bug] Failed to get OrderBook for symbol

### ISSUE THREAD

**Issue by demanuPL** [gabriel-milan/btrader#10]
I see this on each pair:

`thread '<unnamed>' panicked at 'Failed to get OrderBook for symbol SXPAUD. Error: error sending request for url (https://api.binance.com/api/v3/depth?symbol=SXPAUD&limit=100): error trying to connect: tcp connect error: No route to host (os error 113)', src/depth_cache.rs:166:15
`

**Comment by gabriel-milan** [comment]
Hi @demanuPL thanks for getting in touch!

It seems to be an OS error. Can you confirm that you can ping `api.binance.com` on your machine?

**Comment by demanuPL** [comment]
Hello, thanks for quick respond. Yes there is a 30-40ms ping to api.binance.com

**Comment by gabriel-milan** [comment]
And this is the same machine from which you're trying to run bTrader?

**Comment by demanuPL** [comment]
Yes, native in terminal, no docker

**Comment by gabriel-milan** [comment]
That's really weird. Could you please try running it with `strace` or a similar tool for debugging, as suggested [here](https://stackoverflow.com/questions/10516222/no-route-to-host-error-113/42164590)? I can't reproduce this issue.

**Comment by demanuPL** [comment]
The log output has 30MB, there is problem with pasting it

**Comment by gabriel-milan** [comment]
Could you upload it somewhere, so I can download it?

**Comment by sadsad1314** [comment]
I have such issue also, but not sure is magic or what, if config USDT will never work
If config BTC you'll need to re-run btrader to get it works
