### ISSUE TITLE
Ran into issue with openssl during install and resolved  

### ISSUE THREAD

**Issue by ketzah** [gabriel-milan/btrader#12]
When running step 3 on recommended compile and install method on Raspberry Pi 4

I was getting strange errors, and the build failed due to openssl.

I tried updating and even manually compiling openssl 1.0.1 and didn't work.

What did work is:
`sudo apt-get install pkg-config libssl-dev`

then after running 
`cargo install --path .`
it completed as expected without errors

**Comment by gabriel-milan** [comment]
Hi there!

This is, unfortunately, a well known issue with Raspberry Pi. Please take a look at this cross-compiling guide:
http://web.archive.org/web/20160615142933/https://thekerneldiaries.com/2016/06/14/cross-compile-openssl-for-your-raspberry-pi/

Btw, it's always good to enforce: latency is crucial for getting good results, I'd recommend you rent a server in Tokyo or something.
