### ISSUE TITLE
AJUDA INSTALAÇÃO

### ISSUE THREAD

**Issue by sitespagando** [gabriel-milan/btrader#2]
Olá gabriel tudo bem?

Pode me ajudar a instalar? Não consegui, o projeto ainda funciona?

Tenho interesse em testar

**Comment by gabriel-milan** [comment]
Olá. O projeto está parado no momento devido ao tempo escasso para desenvolvimento do mesmo. No entanto, você pode testar a última versão estável, que ainda deve funcionar. Qual problema está tendo na instalação?

**Comment by sitespagando** [comment]
Poderia me enviar o passo a passo?

Eu segui o que está disponível mais está muito simples e não ensinou passo a passo e não consegui fazer pegar.


________________________________

**Comment by gabriel-milan** [comment]
Você possui um arquivo de configuração editado para seus propósitos? Caso possua, pretende executar via Docker ou Python Shell? Eu não me recordo em que momento do desenvolvimento eu parei, mas se não estiver funcionando talvez consiga olhar isso essa semana. Vale lembrar também que o uso é por conta e risco, não me responsabilizo pelos resultados e que recomendo desabilitar o trade no início, de modo a apenas visualizar as transações que pudessem aparecer.

**Comment by sitespagando** [comment]
Eu uso python.

Sim entendo , só gostaria de testar.

se puder me enviar o passo a passo mais completo ficarei grato.

**Comment by gabriel-milan** [comment]
Usando Python talvez você tenha problemas ao instalar com pip, porque ele precisa compilar o código C++ na sua máquina e talvez estejam faltando algumas bibliotecas pra você. A questão é que de fato não há mais o que detalhar sobre o passo a passo, infelizmente. Caso você consiga expressar os problemas que está tendo, talvez consiga te ajudar. Você também pode tentar usar a imagem Docker, se for o caso.
