### ISSUE TITLE
linker `link.exe` not found

### ISSUE THREAD

**Issue by anony4xmykel** [gabriel-milan/btrader#8]
How do I fix the error 
![error](https://user-images.githubusercontent.com/80187781/110229364-cbbfbc00-7f00-11eb-9f0e-361f6cb58329.PNG)

**Comment by gabriel-milan** [comment]
Hi there.

It seems to be an issue with you Windows environment. Maybe [this answer from StackOverflow](https://stackoverflow.com/a/55603112/9944075) can help you out!
